sources:
- type: rss
  url: https://forum.level1techs.com/latest.rss
  brand_name: Level1Techs (Forum)
  tags: [custom, rss, hardware]
- type: rss
  url: https://www.tweaktown.com/feeds/news-mf.xml
  brand_name: TweakTown
  tags: [custom, rss, hardware]
- type: rss
  url: https://feeds.feedburner.com/pcmag
  brand_name: PCMag
  tags: [custom, rss, tech]
- type: rss
  url: https://technode.com/feed/
  brand_name: TechNode (China Tech)
  tags: [custom, rss, asia]
- type: rss
  url: https://appleinsider.com/rss/news
  brand_name: AppleInsider (News)
  tags: [custom, rss, apple]
- type: rss
  url: https://feeds.feedburner.com/venturebeat/SZYF
  brand_name: VentureBeat
  tags: [custom, rss, business]
- type: rss
  url: https://clickhouse.com/rss.xml
  brand_name: ClickHouse Blog
  tags: [custom, rss, databases]
- type: rss
  url: https://blog.google/technology/ai/rss/?hl=en
  brand_name: Google AI Blog
  tags: [custom, rss, ai]
- type: rss
  url: https://www.digitaltrends.com/feed/rss/
  brand_name: Digital Trends
  tags: [custom, rss, tech]
- type: rss
  url: https://www.techpowerup.com/rss/news
  brand_name: TechPowerUp (News)
  tags: [custom, rss, hardware]
- type: rss
  url: https://electrek.co/feed/
  brand_name: Electrek (EV)
  tags: [custom, rss, ev]
- type: rss
  url: https://www.csoonline.com/feed/
  brand_name: CSO Online
  tags: [custom, rss, security]
- type: rss
  url: https://www.bleepingcomputer.com/feed/
  brand_name: BleepingComputer
  tags: [custom, rss, security]
- type: rss
  url: https://www.darkreading.com/rss.xml
  brand_name: Dark Reading
  tags: [custom, rss, security]
- type: rss
  url: https://securelist.com/feed/
  brand_name: Securelist (Kaspersky)
  tags: [custom, rss, security]
- type: rss
  url: https://www.theguardian.com/technology/rss
  brand_name: The Guardian Technology
  tags: [custom, rss, news]
- type: rss
  url: https://blog.google/rss/?hl=en
  brand_name: Google Keyword Blog
  tags: [custom, rss, news]
- type: rss
  url: https://blogs.oracle.com/mysql/rss
  brand_name: MySQL Blog
  tags: [custom, rss, databases]
- type: rss
  url: https://unity.com/blog/rss
  brand_name: Unity Blog
  tags: [custom, rss, games]
- type: rss
  url: https://blog.adafruit.com/feed/
  brand_name: Adafruit Blog
  tags: [custom, rss, maker]
- type: rss
  url: https://www.exploit-db.com/rss.xml
  brand_name: Exploit Database
  tags: [custom, rss, security]
- type: rss
  url: https://www.cisa.gov/cybersecurity-advisories/cybersecurity-advisories.xml
  brand_name: CISA Cybersecurity Advisories
  tags: [custom, rss, security]
- type: rss
  url: https://www.tomshardware.com/feeds/all
  brand_name: Tom's Hardware
  tags: [custom, rss, hardware]
